import{a as h,S as w,i as l}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&a(p)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const b="48639504-554e542bc8495b3a6c3499497",L="https://pixabay.com/api/";async function f(s,t=1,r=15){try{return(await h.get(L,{params:{key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r}})).data}catch(a){throw console.error("Помилка при отриманні даних з API:",a),a}}const m=document.querySelector(".gallery");let S=new w(".gallery a",{captionsData:"alt",captionDelay:250});function g(s){const t=s.map(r=>`
      <li class="image">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" class="gallery-image" width="360" height="200">
          <div class="imageStats">
            <p><span>Likes</span> ${r.likes}</p>
            <p><span>Views</span> ${r.views}</p>
            <p><span>Comments</span> ${r.comments}</p>
            <p><span>Downloads</span> ${r.downloads}</p>
          </div>
        </a>
      </li>`).join("");m.insertAdjacentHTML("beforeend",t),S.refresh()}function v(){m.innerHTML=""}const u=document.querySelector(".form"),q=document.querySelector(".inputText"),d=document.querySelector(".loader"),n=document.querySelector(".load-more");let c="",i=1;const y=15;u.addEventListener("submit",async s=>{if(s.preventDefault(),c=q.value.trim(),!c){l.warning({title:"Warning",message:"Please enter a search query!"});return}v(),i=1,n.style.display="none",d.style.display="block";try{const t=await f(c,i,y);t.hits.length===0?l.error({title:"Error",message:"Sorry, no images found. Try another search."}):(g(t.hits),t.totalHits>y&&(n.style.display="block"))}catch{l.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{d.style.display="none"}u.reset()});n.addEventListener("click",async()=>{i+=1,n.style.display="none",d.style.display="block";try{const s=await f(c,i,y);g(s.hits),i*y>=s.totalHits?(l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),n.style.display="none"):n.style.display="block";const{height:t}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{l.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{d.style.display="none"}});
//# sourceMappingURL=index.js.map
